swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger ReST Article
consumes:
  - application/json
produces:
  - application/json

basePath: /api

# Paths supported by the server application
paths:
  /block/{blockHash}:
    get:
      operationId: src.endpoints.blocks.read_block
      tags:
        - blocks
      summary: Get information about a block specified by its hash
      description: Get information about a block specified by its hash
      parameters:
        - name: blockHash
          in: path
          description: Unique hash of a block
          type: string
          required: True
      responses:
        200:
          description: Successfully gathered 
          schema:
            properties:
              item1:
                type: string
              item2:
                type: string
              item3:
                type: string