version: '3.3'
services:
  ebe:
    build:
      context: ./container
      dockerfile: Dockerfile
    image: ethereum-explorer
    container_name: ethereum-explorer
    restart: always
    command:
      -printtoconsole
    ports:
      - 5000:5000
    volumes:
      - /home/lgallovi/Documents/ethereum:/home/ethereum
      - /home/lgallovi/Documents/database:/home/db
      - /home/lgallovi/Documents/data:/home/data