version: '3.3'
services:
  ebe:
    build:
      context: ./
      dockerfile: Dockerfile
    image: ethereum-explorer
    container_name: ethereum-explorer
    restart: always
    command:
      -printtoconsole
    network_mode: "host"
    volumes:
      - /home/ethereum:/home/ethereum
      - /home/db:/home/db
      - /home/data:/home/data